server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciamentoimoveispi
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# Cloudflare R2 (preencha com suas credenciais)
cloudflare.r2.access-key=44c48d0253b9c4f52cda658eaceb2c0b
cloudflare.r2.secret-key=2b9d56e360562aba6542690cbc59047f92ed766badfa14bc1ff77db47d1ad5fe
cloudflare.r2.bucket=documents-images
cloudflare.r2.endpoint=https://ba95d5b91ac1eff802f8f492273e555c.r2.cloudflarestorage.com
cloudflare.r2.public-url=https://pub-729e80d6f89c4aef9a2a9b2f71415a15.r2.dev